### ISSUE TITLE
自動從 URL 填入提示的功能好像失效了

### ISSUE THREAD

**Issue by johnson86tw** [doggy8088/ChatGPTToolkitExtension#7]
版本：0.17.0

https://github.com/doggy8088/ChatGPTToolkitExtension/assets/31992185/1acb0732-5bb6-49d2-87bb-267627111fcd

**Comment by abc0922001** [comment]
因為 ChatGPT 改域名了，已經更新好了 #6

**Comment by johnson86tw** [comment]
已更新為 v0.18.0 但還是無法正常運作

**Comment by johnson86tw** [comment]
同樣 v0.18.0 今天用就正常了！

**Comment by doggy8088** [comment]
@johnson86tw Chrome 有時候升級套件會載入異常，重新關閉重啟就會好了
